/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "common_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sysReq, sysReq, AUTO)


PB_BIND(sysRsp, sysRsp, AUTO)



