/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "diot_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DataDetail, DataDetail, AUTO)


PB_BIND(DataDps, DataDps, AUTO)


PB_BIND(DataContent, DataContent, AUTO)


PB_BIND(Body, Body, AUTO)



