/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "route_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(activeReq, activeReq, AUTO)


PB_BIND(activeRsp, activeRsp, AUTO)


PB_BIND(activeRspData, activeRspData, AUTO)


PB_BIND(activeConfirmReq, activeConfirmReq, AUTO)


PB_BIND(activeConfirmRsp, activeConfirmRsp, AUTO)


PB_BIND(routeReq, routeReq, AUTO)


PB_BIND(routeRsp, routeRsp, AUTO)


PB_BIND(routeData, routeData, AUTO)



