/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "tsl_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(property, property, AUTO)


PB_BIND(propPostReq, propPostReq, AUTO)


PB_BIND(propGetReq, propGetReq, AUTO)


PB_BIND(propGetReqParams, propGetReqParams, AUTO)


PB_BIND(propGetRsp, propGetRsp, AUTO)


PB_BIND(propSetReq, propSetReq, AUTO)


PB_BIND(propSetRsp, propSetRsp, AUTO)


PB_BIND(slotDetail, slotDetail, AUTO)


PB_BIND(stakeDetail, stakeDetail, AUTO)


PB_BIND(stateInfoReq, stateInfoReq, AUTO)


PB_BIND(stateParams, stateParams, AUTO)


PB_BIND(chargingInfoReq, chargingInfoReq, AUTO)


PB_BIND(chargingInfoParams, chargingInfoParams, AUTO)


PB_BIND(hardwareWarnReq, hardwareWarnReq, AUTO)


PB_BIND(hardwareWarnParams, hardwareWarnParams, AUTO)


PB_BIND(hardwareWarnServiceReq, hardwareWarnServiceReq, AUTO)


PB_BIND(hardwareWarnServiceParams, hardwareWarnServiceParams, AUTO)


PB_BIND(hardwareWarnServiceRsp, hardwareWarnServiceRsp, AUTO)


PB_BIND(manualReportReq, manualReportReq, AUTO)


PB_BIND(manualReportParams, manualReportParams, AUTO)


PB_BIND(manualReportRsp, manualReportRsp, AUTO)


PB_BIND(enableChargeReq, enableChargeReq, AUTO)


PB_BIND(enableChargeParams, enableChargeParams, AUTO)


PB_BIND(enableChargeRsp, enableChargeRsp, AUTO)


PB_BIND(disableChargeReq, disableChargeReq, AUTO)


PB_BIND(disableChargeParams, disableChargeParams, AUTO)


PB_BIND(disableChargeRsp, disableChargeRsp, AUTO)








